version: "3.4"

services:
  db:
    image: mysql:latest
    restart: always
    container_name: msago-sample-db
    ports:
      - "33551:3306"
    environment:
      - MYSQL_DATABASE=sakila
      - MYSQL_ROOT_PASSWORD=1
      - TZ=Asia/Seoul
    volumes:
      - ../sql:/docker-entrypoint-initdb.d
